In [6]:
import streamlit as st
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
from datetime import datetime 


st.write("""
# My first app
Hello *world!*
""")
 
application_test = pd.read_csv("input/application_test.csv")
application_train = pd.read_csv("input/application_train.csv")
application_test
#msno.bar(application_test, figsize=(10,2))

#st.line_chart(df)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48739,456221,Cash loans,F,N,Y,0,121500.0,412560.0,17473.5,270000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
48740,456222,Cash loans,F,N,N,2,157500.0,622413.0,31909.5,495000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
48741,456223,Cash loans,F,Y,Y,1,202500.0,315000.0,33205.5,315000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,3.0,1.0
48742,456224,Cash loans,M,N,N,0,225000.0,450000.0,25128.0,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
48743,456250,Cash loans,F,Y,N,0,135000.0,312768.0,24709.5,270000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0

## 2. Pipeline

In [1]:
import torch
from transformers import CamembertForSequenceClassification, CamembertTokenizer
 
 
# Chargement du model
state_dict = torch.load("./sentiments.pt")
MODEL = #TODO
# Chargement du tokenizer
TOKENIZER = #TODO
 
def encode(reviews, tokenizer=TOKENIZER):
    encoded_batch = tokenizer.encode_plus([reviews],
                                        add_special_tokens=True,
                                        pad_to_max_length=True,
                                        return_attention_mask=True,
                                        return_tensors = 'pt')
 
    return encoded_batch['input_ids'], encoded_batch['attention_mask']
 
def decode(encoded_results):
    """
    Transforme 0 et 1 respectivement en "negatif" et "positif"
    """
    # On rÃ©cupÃ¨re le scalair contenu dans le tensor
    encoded_results = encoded_results.item()
    if encoded_results == 1:
        return "Positif"
    return "NÃ©gatif"
 
def predict(reviews, model=MODEL, tokenizer=TOKENIZER):
    with torch.no_grad():
        model.eval()
        input_ids, attention_mask = encode(reviews)
        output = model(input_ids, attention_mask=attention_mask)
         
        return decode(torch.argmax(output[0], dim=1))

FileNotFoundError: [Errno 2] No such file or directory: './sentiments.pt'

## 3. Serveur Flask

In [ ]:
import pipeline
from flask import Flask, jsonify, request
 
 
app = Flask(__name__)
 
@app.route("/predict", methods=['GET'])
def get_prediction():
    text = request.args.get('text')
    polarity = pipeline.predict(text)
 
    return jsonify(polarity=polarity)
 
if __name__ == '__main__':
    app.run()